apiVersion: k3d.io/v1alpha2
kind: Simple
servers: 1
image: docker.io/rancher/k3s:v1.20.4-k3s1
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 9000:9000
    nodeFilters:
      - loadbalancer
  - port: 8080:8080
    nodeFilters:
      - loadbalancer
  - port: 8082:8082
    nodeFilters:
      - loadbalancer
  - port: 8582:30082
    nodeFilters:
      - server[0]
  - port: 8583:30083
    nodeFilters:
      - server[0]
options:
  k3s:
    extraServerArgs:
      - --no-deploy=traefik
kubeAPI:
  hostIP: "127.0.0.1"
  hostPort: "6443"
registries:
  create: true
    
