kind: Service
apiVersion: v1
metadata:
  name: user-repository-debug
spec:
  type: NodePort
  selector:
    app: user-repository
  ports:
    - name: http
      protocol: TCP
      port: 8582
      nodePort: 30082
      targetPort: 8582
      