apiVersion: skaffold/v2beta19
kind: Config
metadata:
  name: user-repository
build:
  artifacts:
  - image: markoniemi/user-repository
    jib:
      project: org.k3s.demo:user-repository
deploy:
  kustomize:
    paths:
    - k8s\dev
profiles:
- name: base
  deploy:
    kustomize:
      paths:
      - k8s\base
- name: external-db
  deploy:
    kustomize:
      paths:
      - k8s\external-db
- name: external-user-repository
  deploy:
    kustomize:
      paths:
      - k8s\external-user-repository
