apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: user-repository
build:
  local:
    push: false 
  artifacts:
    - image: markoniemi/user-repository
      context: .
      jib:
        type: maven 
        args:
          - "jib:buildTar"
deploy:
  kustomize:
    paths: 
      - k8s/dev



    