kind: Service
apiVersion: v1
metadata:
  name: user-repository
spec:
#  type: ExternalName
#  externalName: 172.20.0.1
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8082
      name: user-repository
---
kind: Endpoints
apiVersion: v1
metadata:
  name: user-repository
subsets:
  - addresses:
      - ip: 172.20.0.1
    ports:
      - port: 8082
        name: user-repository
