#kind: Service
#apiVersion: v1
#metadata:
#  name: user-repository
#spec:
#  type: ExternalName
#  externalName: host.k3d.internal
#  ports:
#  - port: 8082
#    targetPort: 8082

kind: Service
apiVersion: v1
metadata:
  name: user-repository
spec:
  type: ClusterIP
  ports:
    - port: 8082
      name: user-repository
