kind: Deployment
apiVersion: apps/v1
metadata:
  name: user-repository
spec:
  selector:
      matchLabels:
        app: user-repository
  replicas: 1
  strategy:
    # use Recreate strategy if older version of app is not compatible with new db
    #type: Recreate
  template:
    metadata:
      labels:
        app: user-repository
    spec:
      containers:
        - name: user-repository
          image: markoniemi/user-repository:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 8082
          env:
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: user-repository
                key: DB_USERNAME
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: user-repository
                key: DB_PASSWORD
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
            initialDelaySeconds: 10
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
            initialDelaySeconds: 10
            periodSeconds: 3
            failureThreshold: 2
