kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: user-repository
  annotations:
    ingress.kubernetes.io/rewrite-target: /api
spec:
  rules:
  - http:
      paths:
      - path: /users/api
        pathType: Prefix
        backend:
          service:
            name: user-repository
            port:
              number: 8082
