kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: user-repository
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /api/$2
spec:
  rules:
  - http:
      paths:
      - path: /users/api(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: user-repository
            port:
              number: 8082
