apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- secret.yaml
- configMap.yaml
configMapGenerator:
- name: user-repository
  behavior: merge
  files:
    - application.properties
    - bootstrap.yml
    - log4j2.xml
commonLabels:
  app: user-repository
